// AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
// Generated from index.html

window.ELEMENTS_DATA = [
  {
    "id": "H",
    "symbol": "H",
    "name": "Hydrogen",
    "atomicNumber": 1,
    "mass": 1.008,
    "group": "1A",
    "period": 1,
    "block": "s",
    "category": "nonmetal",
    "state": "Gas",
    "appearance": "colorless gas",
    "density": 0.00008988,
    "meltingPoint": 13.81,
    "boilingPoint": 20.28,
    "electronegativity": 2.2,
    "electronAffinity": 0.754,
    "ionizationEnergy": 13.598,
    "atomicRadius": 120,
    "configuration": "1s¹",
    "magnetic": "diamagnetic",
    "discoverer": "Henry Cavendish",
    "discoveryYear": 1766
  },
  {
    "id": "He",
    "symbol": "He",
    "name": "Helium",
    "atomicNumber": 2,
    "mass": 4.0026,
    "group": "8A",
    "period": 1,
    "block": "s",
    "category": "noble gas",
    "state": "Gas",
    "appearance": "colorless gas",
    "density": 0.0001785,
    "meltingPoint": 0.95,
    "boilingPoint": 4.22,
    "electronegativity": "-",
    "electronAffinity": "-",
    "ionizationEnergy": 24.587,
    "atomicRadius": 140,
    "configuration": "1s²",
    "magnetic": "diamagnetic",
    "discoverer": "Norman Lockyer",
    "discoveryYear": 1868
  },
  {
    "id": "Li",
    "symbol": "Li",
    "name": "Lithium",
    "atomicNumber": 3,
    "mass": 7.0,
    "group": "1A",
    "period": 2,
    "block": "s",
    "category": "alkali metal",
    "state": "Solid",
    "appearance": "silvery-white metal",
    "density": 0.534,
    "meltingPoint": 453.65,
    "boilingPoint": 1615,
    "electronegativity": 0.98,
    "electronAffinity": 0.618,
    "ionizationEnergy": 5.392,
    "atomicRadius": 182,
    "configuration": "1s² 2s¹",
    "magnetic": "paramagnetic",
    "discoverer": "Johan August Arfwedson",
    "discoveryYear": 1817
  },
  {
    "id": "Be",
    "symbol": "Be",
    "name": "Beryllium",
    "atomicNumber": 4,
    "mass": 9.012183,
    "group": "2A",
    "period": 2,
    "block": "s",
    "category": "alkaline earth metal",
    "state": "Solid",
    "appearance": "steel gray metal",
    "density": 1.85,
    "meltingPoint": 1560,
    "boilingPoint": 2744,
    "electronegativity": 1.57,
    "electronAffinity": "-",
    "ionizationEnergy": 9.322,
    "atomicRadius": 153,
    "configuration": "1s² 2s²",
    "magnetic": "diamagnetic",
    "discoverer": "Louis Nicolas Vauquelin",
    "discoveryYear": 1798
  },
  {
    "id": "B",
    "symbol": "B",
    "name": "Boron",
    "atomicNumber": 5,
    "mass": 10.81,
    "group": "3A",
    "period": 2,
    "block": "p",
    "category": "metalloid",
    "state": "Solid",
    "appearance": "black-brown solid",
    "density": 2.37,
    "meltingPoint": 2348,
    "boilingPoint": 4273,
    "electronegativity": 2.04,
    "electronAffinity": 0.277,
    "ionizationEnergy": 8.298,
    "atomicRadius": 192,
    "configuration": "1s² 2s² 2p¹",
    "magnetic": "diamagnetic",
    "discoverer": "Joseph Louis Gay-Lussac & Louis Jacques Thénard",
    "discoveryYear": 1808
  },
  {
    "id": "C",
    "symbol": "C",
    "name": "Carbon",
    "atomicNumber": 6,
    "mass": 12.011,
    "group": "4A",
    "period": 2,
    "block": "p",
    "category": "nonmetal",
    "state": "Solid",
    "appearance": "black (graphite) or transparent (diamond) solid",
    "density": 2.267,
    "meltingPoint": 3823,
    "boilingPoint": 4098,
    "electronegativity": 2.55,
    "electronAffinity": 1.263,
    "ionizationEnergy": 11.26,
    "atomicRadius": 170,
    "configuration": "1s² 2s² 2p²",
    "magnetic": "diamagnetic",
    "discoverer": "Egyptians & Sumerians",
    "discoveryYear": "3750 BC"
  },
  {
    "id": "N",
    "symbol": "N",
    "name": "Nitrogen",
    "atomicNumber": 7,
    "mass": 14.007,
    "group": "5A",
    "period": 2,
    "block": "p",
    "category": "nonmetal",
    "state": "Gas",
    "appearance": "colorless gas",
    "density": 0.0012506,
    "meltingPoint": 63.15,
    "boilingPoint": 77.36,
    "electronegativity": 3.04,
    "electronAffinity": "-",
    "ionizationEnergy": 14.534,
    "atomicRadius": 155,
    "configuration": "1s² 2s² 2p³",
    "magnetic": "diamagnetic",
    "discoverer": "Daniel Rutherford",
    "discoveryYear": 1772
  },
  {
    "id": "O",
    "symbol": "O",
    "name": "Oxygen",
    "atomicNumber": 8,
    "mass": 15.999,
    "group": "6A",
    "period": 2,
    "block": "p",
    "category": "nonmetal",
    "state": "Gas",
    "appearance": "colorless gas",
    "density": 0.001429,
    "meltingPoint": 54.36,
    "boilingPoint": 90.2,
    "electronegativity": 3.44,
    "electronAffinity": 1.461,
    "ionizationEnergy": 13.618,
    "atomicRadius": 152,
    "configuration": "1s² 2s² 2p⁴",
    "magnetic": "paramagnetic",
    "discoverer": "Michael Sendivogius, Carl Wilhelm Scheele",
    "discoveryYear": "1604, 1771"
  },
  {
    "id": "F",
    "symbol": "F",
    "name": "Fluorine",
    "atomicNumber": 9,
    "mass": 18.99840316,
    "group": "7A",
    "period": 2,
    "block": "p",
    "category": "halogen",
    "state": "Gas",
    "appearance": "pale yellow gas",
    "density": 0.001696,
    "meltingPoint": 53.53,
    "boilingPoint": 85.03,
    "electronegativity": 3.98,
    "electronAffinity": 3.339,
    "ionizationEnergy": 17.423,
    "atomicRadius": 135,
    "configuration": "1s² 2s² 2p⁵",
    "magnetic": "diamagnetic",
    "discoverer": "André-Marie Ampère",
    "discoveryYear": 1810
  },
  {
    "id": "Ne",
    "symbol": "Ne",
    "name": "Neon",
    "atomicNumber": 10,
    "mass": 20.18,
    "group": "8A",
    "period": 2,
    "block": "p",
    "category": "noble gas",
    "state": "Gas",
    "appearance": "colorless gas",
    "density": 0.0008999,
    "meltingPoint": 24.56,
    "boilingPoint": 27.07,
    "electronegativity": "-",
    "electronAffinity": "-",
    "ionizationEnergy": 21.564,
    "atomicRadius": 154,
    "configuration": "1s² 2s² 2p⁶",
    "magnetic": "diamagnetic",
    "discoverer": "William Ramsay & Morris Travers",
    "discoveryYear": 1898
  },
  {
    "id": "Na",
    "symbol": "Na",
    "name": "Sodium",
    "atomicNumber": 11,
    "mass": 22.9897693,
    "group": "1A",
    "period": 3,
    "block": "s",
    "category": "alkali metal",
    "state": "Solid",
    "appearance": "silvery-white metal",
    "density": 0.97,
    "meltingPoint": 370.95,
    "boilingPoint": 1156,
    "electronegativity": 0.93,
    "electronAffinity": 0.548,
    "ionizationEnergy": 5.139,
    "atomicRadius": 227,
    "configuration": "1s² 2s² 2p⁶ 3s¹",
    "magnetic": "paramagnetic",
    "discoverer": "Humphry Davy",
    "discoveryYear": 1807
  },
  {
    "id": "Mg",
    "symbol": "Mg",
    "name": "Magnesium",
    "atomicNumber": 12,
    "mass": 24.305,
    "group": "2A",
    "period": 3,
    "block": "s",
    "category": "alkaline earth metal",
    "state": "Solid",
    "appearance": "silvery-white metal",
    "density": 1.74,
    "meltingPoint": 923,
    "boilingPoint": 1363,
    "electronegativity": 1.31,
    "electronAffinity": "-",
    "ionizationEnergy": 7.646,
    "atomicRadius": 173,
    "configuration": "1s² 2s² 2p⁶ 3s²",
    "magnetic": "paramagnetic",
    "discoverer": "Joseph Black",
    "discoveryYear": 1755
  },
  {
    "id": "Al",
    "symbol": "Al",
    "name": "Aluminium",
    "atomicNumber": 13,
    "mass": 26.981538,
    "group": "3A",
    "period": 3,
    "block": "p",
    "category": "metal",
    "state": "Solid",
    "appearance": "silvery-white metal",
    "density": 2.7,
    "meltingPoint": 933.437,
    "boilingPoint": 2792,
    "electronegativity": 1.61,
    "electronAffinity": 0.441,
    "ionizationEnergy": 5.986,
    "atomicRadius": 184,
    "configuration": "1s² 2s² 2p⁶ 3s² 3p¹",
    "magnetic": "paramagnetic",
    "discoverer": "Hans Christian Ørsted",
    "discoveryYear": 1824
  },
  {
    "id": "Si",
    "symbol": "Si",
    "name": "Silicon",
    "atomicNumber": 14,
    "mass": 28.085,
    "group": "4A",
    "period": 3,
    "block": "p",
    "category": "metalloid",
    "state": "Solid",
    "appearance": "gray solid",
    "density": 2.3296,
    "meltingPoint": 1687,
    "boilingPoint": 3538,
    "electronegativity": 1.9,
    "electronAffinity": 1.385,
    "ionizationEnergy": 8.152,
    "atomicRadius": 210,
    "configuration": "1s² 2s² 2p⁶ 3s² 3p²",
    "magnetic": "diamagnetic",
    "discoverer": "Jöns Jacob Berzelius",
    "discoveryYear": 1823
  },
  {
    "id": "P",
    "symbol": "P",
    "name": "Phosphorus",
    "atomicNumber": 15,
    "mass": 30.973762,
    "group": "5A",
    "period": 3,
    "block": "p",
    "category": "nonmetal",
    "state": "Solid",
    "appearance": "yellow (white phosphorus) or red (red phosphorus) solid",
    "density": 1.82,
    "meltingPoint": 317.3,
    "boilingPoint": 553.65,
    "electronegativity": 2.19,
    "electronAffinity": 0.746,
    "ionizationEnergy": 10.487,
    "atomicRadius": 180,
    "configuration": "1s² 2s² 2p⁶ 3s² 3p³",
    "magnetic": "diamagnetic",
    "discoverer": "Hennig Brand",
    "discoveryYear": 1669
  },
  {
    "id": "S",
    "symbol": "S",
    "name": "Sulfur",
    "atomicNumber": 16,
    "mass": 32.07,
    "group": "6A",
    "period": 3,
    "block": "p",
    "category": "nonmetal",
    "state": "Solid",
    "appearance": "yellow solid",
    "density": 2.067,
    "meltingPoint": 388.36,
    "boilingPoint": 717.75,
    "electronegativity": 2.58,
    "electronAffinity": 2.077,
    "ionizationEnergy": 10.36,
    "atomicRadius": 180,
    "configuration": "1s² 2s² 2p⁶ 3s² 3p⁴",
    "magnetic": "diamagnetic",
    "discoverer": "Unknown",
    "discoveryYear": "before 2000 BC"
  },
  {
    "id": "Cl",
    "symbol": "Cl",
    "name": "Chlorine",
    "atomicNumber": 17,
    "mass": 35.45,
    "group": "7A",
    "period": 3,
    "block": "p",
    "category": "halogen",
    "state": "Gas",
    "appearance": "greenish-yellow gas",
    "density": 0.003214,
    "meltingPoint": 171.65,
    "boilingPoint": 239.11,
    "electronegativity": 3.16,
    "electronAffinity": 3.617,
    "ionizationEnergy": 12.968,
    "atomicRadius": 175,
    "configuration": "1s² 2s² 2p⁶ 3s² 3p⁵",
    "magnetic": "diamagnetic",
    "discoverer": "Carl Wilhelm Scheele",
    "discoveryYear": 1774
  },
  {
    "id": "Ar",
    "symbol": "Ar",
    "name": "Argon",
    "atomicNumber": 18,
    "mass": 39.9,
    "group": "8A",
    "period": 3,
    "block": "p",
    "category": "noble gas",
    "state": "Gas",
    "appearance": "colorless gas",
    "density": 0.0017837,
    "meltingPoint": 83.8,
    "boilingPoint": 87.3,
    "electronegativity": "-",
    "electronAffinity": "-",
    "ionizationEnergy": 15.76,
    "atomicRadius": 188,
    "configuration": "1s² 2s² 2p⁶ 3s² 3p⁶",
    "magnetic": "diamagnetic",
    "discoverer": "Lord Rayleigh & William Ramsay",
    "discoveryYear": 1894
  },
  {
    "id": "K",
    "symbol": "K",
    "name": "Potassium",
    "atomicNumber": 19,
    "mass": 39.0983,
    "group": "1A",
    "period": 4,
    "block": "s",
    "category": "alkali metal",
    "state": "Solid",
    "appearance": "silvery metal",
    "density": 0.89,
    "meltingPoint": 336.53,
    "boilingPoint": 1032,
    "electronegativity": 0.82,
    "electronAffinity": 0.501,
    "ionizationEnergy": 4.341,
    "atomicRadius": 275,
    "configuration": "1s² 2s² 2p⁶ 3s² 3p⁶ 4s¹",
    "magnetic": "paramagnetic",
    "discoverer": "Humphry Davy",
    "discoveryYear": 1807
  },
  {
    "id": "Ca",
    "symbol": "Ca",
    "name": "Calcium",
    "atomicNumber": 20,
    "mass": 40.08,
    "group": "2A",
    "period": 4,
    "block": "s",
    "category": "alkaline earth metal",
    "state": "Solid",
    "appearance": "silvery metal",
    "density": 1.54,
    "meltingPoint": 1115,
    "boilingPoint": 1757,
    "electronegativity": 1.0,
    "electronAffinity": "-",
    "ionizationEnergy": 6.113,
    "atomicRadius": 231,
    "configuration": "1s² 2s² 2p⁶ 3s² 3p⁶ 4s²",
    "magnetic": "diamagnetic",
    "discoverer": "Humphry Davy",
    "discoveryYear": 1808
  },
  {
    "id": "Sc",
    "symbol": "Sc",
    "name": "Scandium",
    "atomicNumber": 21,
    "mass": 44.95591,
    "group": "3B",
    "period": 4,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "silvery-white metal",
    "density": 2.99,
    "meltingPoint": 1814,
    "boilingPoint": 3109,
    "electronegativity": 1.36,
    "electronAffinity": 0.188,
    "ionizationEnergy": 6.561,
    "atomicRadius": 211,
    "configuration": "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹ 4s²",
    "magnetic": "paramagnetic",
    "discoverer": "Lars Fredrik Nilson",
    "discoveryYear": 1879
  },
  {
    "id": "Ti",
    "symbol": "Ti",
    "name": "Titanium",
    "atomicNumber": 22,
    "mass": 47.867,
    "group": "4B",
    "period": 4,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "silvery metal",
    "density": 4.5,
    "meltingPoint": 1941,
    "boilingPoint": 3560,
    "electronegativity": 1.54,
    "electronAffinity": 0.079,
    "ionizationEnergy": 6.828,
    "atomicRadius": 187,
    "configuration": "1s² 2s² 2p⁶ 3s² 3p⁶ 3d² 4s²",
    "magnetic": "paramagnetic",
    "discoverer": "William Gregor",
    "discoveryYear": 1791
  },
  {
    "id": "V",
    "symbol": "V",
    "name": "Vanadium",
    "atomicNumber": 23,
    "mass": 50.9415,
    "group": "5B",
    "period": 4,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "gray metallic solid",
    "density": 6.0,
    "meltingPoint": 2183,
    "boilingPoint": 3680,
    "electronegativity": 1.63,
    "electronAffinity": 0.525,
    "ionizationEnergy": 6.746,
    "atomicRadius": 179,
    "configuration": "1s² 2s² 2p⁶ 3s² 3p⁶ 3d³ 4s²",
    "magnetic": "paramagnetic",
    "discoverer": "Andrés Manuel del Rio",
    "discoveryYear": 1801
  },
  {
    "id": "Cr",
    "symbol": "Cr",
    "name": "Chromium",
    "atomicNumber": 24,
    "mass": 51.996,
    "group": "6B",
    "period": 4,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "silvery metallic solid",
    "density": 7.15,
    "meltingPoint": 2180,
    "boilingPoint": 2944,
    "electronegativity": 1.66,
    "electronAffinity": 0.666,
    "ionizationEnergy": 6.767,
    "atomicRadius": 189,
    "configuration": "1s² 2s² 2p⁶ 3s² 3p⁶ 3d⁵ 4s¹",
    "magnetic": "antiferromagnetic",
    "discoverer": "Louis Nicolas Vauquelin",
    "discoveryYear": 1794
  },
  {
    "id": "Mn",
    "symbol": "Mn",
    "name": "Manganese",
    "atomicNumber": 25,
    "mass": 54.93804,
    "group": "7B",
    "period": 4,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "gray-white metal",
    "density": 7.3,
    "meltingPoint": 1519,
    "boilingPoint": 2334,
    "electronegativity": 1.55,
    "electronAffinity": "-",
    "ionizationEnergy": 7.434,
    "atomicRadius": 197,
    "configuration": "1s² 2s² 2p⁶ 3s² 3p⁶ 3d⁵ 4s²",
    "magnetic": "paramagnetic",
    "discoverer": "Carl Wilhelm Scheele",
    "discoveryYear": 1774
  },
  {
    "id": "Fe",
    "symbol": "Fe",
    "name": "Iron",
    "atomicNumber": 26,
    "mass": 55.84,
    "group": "8B",
    "period": 4,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "lustrous metallic solid",
    "density": 7.874,
    "meltingPoint": 1811,
    "boilingPoint": 3134,
    "electronegativity": 1.83,
    "electronAffinity": 0.163,
    "ionizationEnergy": 7.902,
    "atomicRadius": 194,
    "configuration": "1s² 2s² 2p⁶ 3s² 3p⁶ 3d⁶ 4s²",
    "magnetic": "ferromagnetic",
    "discoverer": "Unknown",
    "discoveryYear": "before 5000 BC"
  },
  {
    "id": "Co",
    "symbol": "Co",
    "name": "Cobalt",
    "atomicNumber": 27,
    "mass": 58.93319,
    "group": "8B",
    "period": 4,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "silvery-gray metal",
    "density": 8.86,
    "meltingPoint": 1768,
    "boilingPoint": 3200,
    "electronegativity": 1.88,
    "electronAffinity": 0.661,
    "ionizationEnergy": 7.881,
    "atomicRadius": 192,
    "configuration": "1s² 2s² 2p⁶ 3s² 3p⁶ 3d⁷ 4s²",
    "magnetic": "ferromagnetic",
    "discoverer": "Georg Brandt",
    "discoveryYear": 1735
  },
  {
    "id": "Ni",
    "symbol": "Ni",
    "name": "Nickel",
    "atomicNumber": 28,
    "mass": 58.693,
    "group": "8B",
    "period": 4,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "lustrous metallic solid",
    "density": 8.912,
    "meltingPoint": 1728,
    "boilingPoint": 3186,
    "electronegativity": 1.91,
    "electronAffinity": 1.156,
    "ionizationEnergy": 7.639,
    "atomicRadius": 163,
    "configuration": "1s² 2s² 2p⁶ 3s² 3p⁶ 3d⁸ 4s²",
    "magnetic": "ferromagnetic",
    "discoverer": "Axel Fredrik Cronstedt",
    "discoveryYear": 1751
  },
  {
    "id": "Cu",
    "symbol": "Cu",
    "name": "Copper",
    "atomicNumber": 29,
    "mass": 63.55,
    "group": "1B",
    "period": 4,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "reddish metallic solid",
    "density": 8.933,
    "meltingPoint": 1357.77,
    "boilingPoint": 2835,
    "electronegativity": 1.9,
    "electronAffinity": 1.228,
    "ionizationEnergy": 7.726,
    "atomicRadius": 140,
    "configuration": "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s¹",
    "magnetic": "diamagnetic",
    "discoverer": "Middle East",
    "discoveryYear": "9000 BC"
  },
  {
    "id": "Zn",
    "symbol": "Zn",
    "name": "Zinc",
    "atomicNumber": 30,
    "mass": 65.4,
    "group": "2B",
    "period": 4,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "bluish-silver metal",
    "density": 7.134,
    "meltingPoint": 692.68,
    "boilingPoint": 1180,
    "electronegativity": 1.65,
    "electronAffinity": "-",
    "ionizationEnergy": 9.394,
    "atomicRadius": 139,
    "configuration": "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s²",
    "magnetic": "diamagnetic",
    "discoverer": "Indian Metallurgists",
    "discoveryYear": "before 1000 BC"
  },
  {
    "id": "Ga",
    "symbol": "Ga",
    "name": "Gallium",
    "atomicNumber": 31,
    "mass": 69.723,
    "group": "3A",
    "period": 4,
    "block": "p",
    "category": "metal",
    "state": "Solid",
    "appearance": "silvery metal",
    "density": 5.91,
    "meltingPoint": 302.91,
    "boilingPoint": 2477,
    "electronegativity": 1.81,
    "electronAffinity": 0.3,
    "ionizationEnergy": 5.999,
    "atomicRadius": 187,
    "configuration": "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p¹",
    "magnetic": "diamagnetic",
    "discoverer": "Lecoq de Boisbaudran",
    "discoveryYear": 1875
  },
  {
    "id": "Ge",
    "symbol": "Ge",
    "name": "Germanium",
    "atomicNumber": 32,
    "mass": 72.63,
    "group": "4A",
    "period": 4,
    "block": "p",
    "category": "metalloid",
    "state": "Solid",
    "appearance": "grayish-white metalloid",
    "density": 5.323,
    "meltingPoint": 1211.4,
    "boilingPoint": 3106,
    "electronegativity": 2.01,
    "electronAffinity": 1.35,
    "ionizationEnergy": 7.899,
    "atomicRadius": 211,
    "configuration": "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p²",
    "magnetic": "diamagnetic",
    "discoverer": "Clemens Winkler",
    "discoveryYear": 1886
  },
  {
    "id": "As",
    "symbol": "As",
    "name": "Arsenic",
    "atomicNumber": 33,
    "mass": 74.92159,
    "group": "5A",
    "period": 4,
    "block": "p",
    "category": "metalloid",
    "state": "Solid",
    "appearance": "metallic gray",
    "density": 5.776,
    "meltingPoint": 1090,
    "boilingPoint": 887,
    "electronegativity": 2.18,
    "electronAffinity": 0.81,
    "ionizationEnergy": 9.815,
    "atomicRadius": 185,
    "configuration": "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p³",
    "magnetic": "diamagnetic",
    "discoverer": "Arabic Alchemists",
    "discoveryYear": "before AD 815"
  },
  {
    "id": "Se",
    "symbol": "Se",
    "name": "Selenium",
    "atomicNumber": 34,
    "mass": 78.97,
    "group": "6A",
    "period": 4,
    "block": "p",
    "category": "nonmetal",
    "state": "Solid",
    "appearance": "gray, red, or black solid",
    "density": 4.809,
    "meltingPoint": 493.65,
    "boilingPoint": 958,
    "electronegativity": 2.55,
    "electronAffinity": 2.021,
    "ionizationEnergy": 9.752,
    "atomicRadius": 190,
    "configuration": "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁴",
    "magnetic": "diamagnetic",
    "discoverer": "Jöns Jakob Berzelius & Johann Gottlieb Gahn",
    "discoveryYear": 1817
  },
  {
    "id": "Br",
    "symbol": "Br",
    "name": "Bromine",
    "atomicNumber": 35,
    "mass": 79.9,
    "group": "7A",
    "period": 4,
    "block": "p",
    "category": "halogen",
    "state": "Liquid",
    "appearance": "reddish-brown liquid",
    "density": 3.11,
    "meltingPoint": 265.95,
    "boilingPoint": 331.95,
    "electronegativity": 2.96,
    "electronAffinity": 3.365,
    "ionizationEnergy": 11.814,
    "atomicRadius": 183,
    "configuration": "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁵",
    "magnetic": "diamagnetic",
    "discoverer": "Antoine Jérôme Balard & Carl Jacob Löwig",
    "discoveryYear": 1825
  },
  {
    "id": "Kr",
    "symbol": "Kr",
    "name": "Krypton",
    "atomicNumber": 36,
    "mass": 83.8,
    "group": "8A",
    "period": 4,
    "block": "p",
    "category": "noble gas",
    "state": "Gas",
    "appearance": "colorless gas",
    "density": 0.003733,
    "meltingPoint": 115.79,
    "boilingPoint": 119.93,
    "electronegativity": 3.0,
    "electronAffinity": "-",
    "ionizationEnergy": 13.999,
    "atomicRadius": 202,
    "configuration": "1s² 2s² 2p⁶ 3s² 3p⁶ 3d¹⁰ 4s² 4p⁶",
    "magnetic": "diamagnetic",
    "discoverer": "William Ramsay & Morris Travers",
    "discoveryYear": 1898
  },
  {
    "id": "Rb",
    "symbol": "Rb",
    "name": "Rubidium",
    "atomicNumber": 37,
    "mass": 85.468,
    "group": "1A",
    "period": 5,
    "block": "s",
    "category": "alkali metal",
    "state": "Solid",
    "appearance": "gray white",
    "density": 1.53,
    "meltingPoint": 312.46,
    "boilingPoint": 961,
    "electronegativity": 0.82,
    "electronAffinity": 0.468,
    "ionizationEnergy": 4.177,
    "atomicRadius": 303,
    "configuration": "[Kr] 5s¹",
    "magnetic": "paramagnetic",
    "discoverer": "Gustav Kirchhoff & Robert Bunsen",
    "discoveryYear": 1861
  },
  {
    "id": "Sr",
    "symbol": "Sr",
    "name": "Strontium",
    "atomicNumber": 38,
    "mass": 87.62,
    "group": "2A",
    "period": 5,
    "block": "s",
    "category": "alkaline earth metal",
    "state": "Solid",
    "appearance": "silvery white-yellow metallic",
    "density": 2.64,
    "meltingPoint": 1050,
    "boilingPoint": 1655,
    "electronegativity": 0.95,
    "electronAffinity": "-",
    "ionizationEnergy": 5.695,
    "atomicRadius": 249,
    "configuration": "[Kr] 5s²",
    "magnetic": "paramagnetic",
    "discoverer": "William Cruickshank",
    "discoveryYear": 1787
  },
  {
    "id": "Y",
    "symbol": "Y",
    "name": "Yttrium",
    "atomicNumber": 39,
    "mass": 88.90584,
    "group": "3B",
    "period": 5,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "silvery white",
    "density": 4.47,
    "meltingPoint": 1795,
    "boilingPoint": 3618,
    "electronegativity": 1.22,
    "electronAffinity": 0.307,
    "ionizationEnergy": 6.217,
    "atomicRadius": 219,
    "configuration": "[Kr] 4d¹ 5s²",
    "magnetic": "paramagnetic",
    "discoverer": "Johan Gadolin",
    "discoveryYear": 1794
  },
  {
    "id": "Zr",
    "symbol": "Zr",
    "name": "Zirconium",
    "atomicNumber": 40,
    "mass": 91.22,
    "group": "4B",
    "period": 5,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "silvery white",
    "density": 6.52,
    "meltingPoint": 2128,
    "boilingPoint": 4682,
    "electronegativity": 1.33,
    "electronAffinity": 0.426,
    "ionizationEnergy": 6.634,
    "atomicRadius": 186,
    "configuration": "[Kr] 4d² 5s²",
    "magnetic": "paramgnetic",
    "discoverer": "Martin Heinrich Klaproth",
    "discoveryYear": 1789
  },
  {
    "id": "Nb",
    "symbol": "Nb",
    "name": "Niobium",
    "atomicNumber": 41,
    "mass": 92.90637,
    "group": "5B",
    "period": 5,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "gray metallic",
    "density": 8.57,
    "meltingPoint": 2750,
    "boilingPoint": 5017,
    "electronegativity": 1.6,
    "electronAffinity": 0.893,
    "ionizationEnergy": 6.759,
    "atomicRadius": 207,
    "configuration": "[Kr] 4d⁴ 5s¹",
    "magnetic": "paramagnetic",
    "discoverer": "Charles Hatchett",
    "discoveryYear": 1801
  },
  {
    "id": "Mo",
    "symbol": "Mo",
    "name": "Molybdenum",
    "atomicNumber": 42,
    "mass": 95.95,
    "group": "6B",
    "period": 5,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "gray metallic",
    "density": 10.2,
    "meltingPoint": 2896,
    "boilingPoint": 4912,
    "electronegativity": 2.16,
    "electronAffinity": 0.746,
    "ionizationEnergy": 7.092,
    "atomicRadius": 209,
    "configuration": "[Kr] 4d⁵ 5s¹",
    "magnetic": "paramagnetic",
    "discoverer": "Carl Wilhelm Scheele",
    "discoveryYear": 1778
  },
  {
    "id": "Tc",
    "symbol": "Tc",
    "name": "Technetium",
    "atomicNumber": 43,
    "mass": 96.90636,
    "group": "7B",
    "period": 5,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "shiny gray metal",
    "density": 11,
    "meltingPoint": 2430,
    "boilingPoint": 4538,
    "electronegativity": 1.9,
    "electronAffinity": 0.55,
    "ionizationEnergy": 7.28,
    "atomicRadius": 209,
    "configuration": "[Kr] 4d⁵ 5s²",
    "magnetic": "paramagnetic",
    "discoverer": "Dimitri Mendeleev",
    "discoveryYear": 1871
  },
  {
    "id": "Ru",
    "symbol": "Ru",
    "name": "Ruthenium",
    "atomicNumber": 44,
    "mass": 101.1,
    "group": "8B",
    "period": 5,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "silvery white metallic",
    "density": 12.1,
    "meltingPoint": 2607,
    "boilingPoint": 4423,
    "electronegativity": 2.2,
    "electronAffinity": 1.05,
    "ionizationEnergy": 7.36,
    "atomicRadius": 207,
    "configuration": "[Kr] 4d⁷ 5s¹",
    "magnetic": "paramagnetic",
    "discoverer": "Karl Ernst Claus",
    "discoveryYear": 1844
  },
  {
    "id": "Rh",
    "symbol": "Rh",
    "name": "Rhodium",
    "atomicNumber": 45,
    "mass": 102.9055,
    "group": "8B",
    "period": 5,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "silvery white metallic",
    "density": 12.4,
    "meltingPoint": 2237,
    "boilingPoint": 3968,
    "electronegativity": 2.28,
    "electronAffinity": 1.137,
    "ionizationEnergy": 7.46,
    "atomicRadius": 195,
    "configuration": "[Kr] 4d⁸ 5s¹",
    "magnetic": "paramagnetic",
    "discoverer": "William Hyde Wollaston",
    "discoveryYear": 1804
  },
  {
    "id": "Pd",
    "symbol": "Pd",
    "name": "Palladium",
    "atomicNumber": 46,
    "mass": 106.42,
    "group": "8B",
    "period": 5,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "silvery white",
    "density": 12.0,
    "meltingPoint": 1828.05,
    "boilingPoint": 3236,
    "electronegativity": 2.2,
    "electronAffinity": 0.557,
    "ionizationEnergy": 8.34,
    "atomicRadius": 202,
    "configuration": "[Kr] 4d¹⁰",
    "magnetic": "paramagnetic",
    "discoverer": "William Hyde Wollaston",
    "discoveryYear": 1802
  },
  {
    "id": "Ag",
    "symbol": "Ag",
    "name": "Silver",
    "atomicNumber": 47,
    "mass": 107.868,
    "group": "1B",
    "period": 5,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "lustrous white metal",
    "density": 10.501,
    "meltingPoint": 1234.93,
    "boilingPoint": 2435,
    "electronegativity": 1.93,
    "electronAffinity": 1.302,
    "ionizationEnergy": 7.576,
    "atomicRadius": 172,
    "configuration": "[Kr] 4d¹⁰ 5s¹",
    "magnetic": "diamagnetic",
    "discoverer": "Unknown",
    "discoveryYear": "before 5000 BC"
  },
  {
    "id": "Cd",
    "symbol": "Cd",
    "name": "Cadmium",
    "atomicNumber": 48,
    "mass": 112.41,
    "group": "2B",
    "period": 5,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "silvery bluish-gray metallic",
    "density": 8.69,
    "meltingPoint": 594.22,
    "boilingPoint": 1040,
    "electronegativity": 1.69,
    "electronAffinity": "-",
    "ionizationEnergy": 8.993,
    "atomicRadius": 158,
    "configuration": "[Kr] 4d¹⁰ 5s²",
    "magnetic": "diamagnetic",
    "discoverer": "Karl Samuel Leberecht Hermann & Friedrich Stromeyer",
    "discoveryYear": 1817
  },
  {
    "id": "In",
    "symbol": "In",
    "name": "Indium",
    "atomicNumber": 49,
    "mass": 114.818,
    "group": "3A",
    "period": 5,
    "block": "p",
    "category": "metal",
    "state": "Solid",
    "appearance": "silvery lustrous gray",
    "density": 7.31,
    "meltingPoint": 429.75,
    "boilingPoint": 2345,
    "electronegativity": 1.78,
    "electronAffinity": 0.3,
    "ionizationEnergy": 5.786,
    "atomicRadius": 193,
    "configuration": "[Kr] 4d¹⁰ 5s² 5p¹",
    "magnetic": "diamagnetic",
    "discoverer": "Ferdinand Reich & Hieronymous Theodor Richter",
    "discoveryYear": 1863
  },
  {
    "id": "Sn",
    "symbol": "Sn",
    "name": "Tin",
    "atomicNumber": 50,
    "mass": 118.71,
    "group": "4A",
    "period": 5,
    "block": "p",
    "category": "metal",
    "state": "Solid",
    "appearance": "silvery white (ß) or gray (α)",
    "density": 7.287,
    "meltingPoint": 505.08,
    "boilingPoint": 2875,
    "electronegativity": 1.96,
    "electronAffinity": 1.2,
    "ionizationEnergy": 7.343,
    "atomicRadius": 217,
    "configuration": "[Kr] 4d¹⁰ 5s² 5p²",
    "magnetic": "diamagnetic (α), paramagnetic (ß)",
    "discoverer": "Unknown",
    "discoveryYear": "~35th century BC"
  },
  {
    "id": "Sb",
    "symbol": "Sb",
    "name": "Antimony",
    "atomicNumber": 51,
    "mass": 121.76,
    "group": "5A",
    "period": 5,
    "block": "p",
    "category": "metalloid",
    "state": "Solid",
    "appearance": "silvery lustrous gray",
    "density": 6.685,
    "meltingPoint": 903.78,
    "boilingPoint": 1860,
    "electronegativity": 2.05,
    "electronAffinity": 1.07,
    "ionizationEnergy": 8.608,
    "atomicRadius": 206,
    "configuration": "[Kr] 4d¹⁰ 5s² 5p³",
    "magnetic": "diamagnetic",
    "discoverer": "Arabic alchemists",
    "discoveryYear": "Before AD 815"
  },
  {
    "id": "Te",
    "symbol": "Te",
    "name": "Tellurium",
    "atomicNumber": 52,
    "mass": 127.6,
    "group": "6A",
    "period": 5,
    "block": "p",
    "category": "metalloid",
    "state": "Solid",
    "appearance": "silvery lustrous gray or brown-black powder",
    "density": 6.232,
    "meltingPoint": 722.66,
    "boilingPoint": 1261,
    "electronegativity": 2.1,
    "electronAffinity": 1.971,
    "ionizationEnergy": 9.009,
    "atomicRadius": 206,
    "configuration": "[Kr] 4d¹⁰ 5s² 5p⁴",
    "magnetic": "diamagnetic",
    "discoverer": "Franz-Joseph Müller von Reichenstein",
    "discoveryYear": 1782
  },
  {
    "id": "I",
    "symbol": "I",
    "name": "Iodine",
    "atomicNumber": 53,
    "mass": 126.9045,
    "group": "7A",
    "period": 5,
    "block": "p",
    "category": "halogen",
    "state": "Solid",
    "appearance": "lustrous metallic gray",
    "density": 4.93,
    "meltingPoint": 386.85,
    "boilingPoint": 457.55,
    "electronegativity": 2.66,
    "electronAffinity": 3.059,
    "ionizationEnergy": 10.451,
    "atomicRadius": 198,
    "configuration": "[Kr] 4d¹⁰ 5s² 5p⁵",
    "magnetic": "diamagnetic",
    "discoverer": "Bernard Courtois",
    "discoveryYear": 1811
  },
  {
    "id": "Xe",
    "symbol": "Xe",
    "name": "Xenon",
    "atomicNumber": 54,
    "mass": 131.29,
    "group": "8A",
    "period": 5,
    "block": "p",
    "category": "noble gas",
    "state": "Gas",
    "appearance": "colorless gas",
    "density": 0.005887,
    "meltingPoint": 161.36,
    "boilingPoint": 165.03,
    "electronegativity": 2.6,
    "electronAffinity": "-",
    "ionizationEnergy": 12.13,
    "atomicRadius": 216,
    "configuration": "[Kr] 4d¹⁰ 5s² 5p⁶",
    "magnetic": "diamagnetic",
    "discoverer": "William Ramsay & Morris Travers",
    "discoveryYear": 1898
  },
  {
    "id": "Cs",
    "symbol": "Cs",
    "name": "Cesium",
    "atomicNumber": 55,
    "mass": 132.905452,
    "group": "1A",
    "period": 6,
    "block": "s",
    "category": "alkali metal",
    "state": "Solid",
    "appearance": "pale gold",
    "density": 1.93,
    "meltingPoint": 301.59,
    "boilingPoint": 944,
    "electronegativity": 0.79,
    "electronAffinity": 0.472,
    "ionizationEnergy": 3.894,
    "atomicRadius": 343,
    "configuration": "[Xe] 6s¹",
    "magnetic": "paramagnetic",
    "discoverer": "Gustav Kirchhoff & Robert Bunsen",
    "discoveryYear": 1860
  },
  {
    "id": "Ba",
    "symbol": "Ba",
    "name": "Barium",
    "atomicNumber": 56,
    "mass": 137.33,
    "group": "2A",
    "period": 6,
    "block": "s",
    "category": "alkaline earth metal",
    "state": "Solid",
    "appearance": "silvery gray with a pale yellow tint",
    "density": 3.62,
    "meltingPoint": 1000,
    "boilingPoint": 2170,
    "electronegativity": 0.89,
    "electronAffinity": "-",
    "ionizationEnergy": 5.211,
    "atomicRadius": 268,
    "configuration": "[Xe] 6s²",
    "magnetic": "paramagnetic",
    "discoverer": "Carl Wilhelm Scheele",
    "discoveryYear": 1772
  },
  {
    "id": "La",
    "symbol": "La",
    "name": "Lanthanum",
    "atomicNumber": 57,
    "mass": 138.9055,
    "group": "Lanthanoids",
    "period": 6,
    "block": "f",
    "category": "lanthanide",
    "state": "Solid",
    "appearance": "silvery white",
    "density": 6.15,
    "meltingPoint": 1191,
    "boilingPoint": 3737,
    "electronegativity": 1.1,
    "electronAffinity": 0.5,
    "ionizationEnergy": 5.576,
    "atomicRadius": 240,
    "configuration": "[Xe] 5d¹ 6s²",
    "magnetic": "paramagnetic",
    "discoverer": "Carl Gustaf Mosander",
    "discoveryYear": 1838
  },
  {
    "id": "Ce",
    "symbol": "Ce",
    "name": "Cerium",
    "atomicNumber": 58,
    "mass": 140.116,
    "group": "Lanthanoids",
    "period": 6,
    "block": "f",
    "category": "lanthanide",
    "state": "Solid",
    "appearance": "silvery white",
    "density": 6.77,
    "meltingPoint": 1071,
    "boilingPoint": 3697,
    "electronegativity": 1.12,
    "electronAffinity": 0.5,
    "ionizationEnergy": 5.538,
    "atomicRadius": 235,
    "configuration": "[Xe] 4f¹ 5d¹ 6s²",
    "magnetic": "paramagnetic",
    "discoverer": "Martin Heinrich Klaproth, Wilhelm Hisinger & Jöns Jakob Berzelius",
    "discoveryYear": 1803
  },
  {
    "id": "Pr",
    "symbol": "Pr",
    "name": "Praseodymium",
    "atomicNumber": 59,
    "mass": 140.90766,
    "group": "Lanthanoids",
    "period": 6,
    "block": "f",
    "category": "lanthanide",
    "state": "Solid",
    "appearance": "grayish white",
    "density": 6.77,
    "meltingPoint": 1204,
    "boilingPoint": 3793,
    "electronegativity": 1.13,
    "electronAffinity": 0.5,
    "ionizationEnergy": 5.473,
    "atomicRadius": 239,
    "configuration": "[Xe] 4f³ 6s²",
    "magnetic": "paramagnetic",
    "discoverer": "Carl Auer von Weisbach",
    "discoveryYear": 1885
  },
  {
    "id": "Nd",
    "symbol": "Nd",
    "name": "Neodymium",
    "atomicNumber": 60,
    "mass": 144.24,
    "group": "Lanthanoids",
    "period": 6,
    "block": "f",
    "category": "lanthanide",
    "state": "Solid",
    "appearance": "silvery white",
    "density": 7.01,
    "meltingPoint": 1294,
    "boilingPoint": 3347,
    "electronegativity": 1.14,
    "electronAffinity": 0.5,
    "ionizationEnergy": 5.525,
    "atomicRadius": 229,
    "configuration": "[Xe] 4f⁴ 6s²",
    "magnetic": "paramagnetic / antiferromagnetc (below 20 K)",
    "discoverer": "Carl Gustaf Mosander",
    "discoveryYear": 1841
  },
  {
    "id": "Pm",
    "symbol": "Pm",
    "name": "Promethium",
    "atomicNumber": 61,
    "mass": 144.91276,
    "group": "Lanthanoids",
    "period": 6,
    "block": "f",
    "category": "lanthanide",
    "state": "Solid",
    "appearance": "metallic",
    "density": 7.26,
    "meltingPoint": 1315,
    "boilingPoint": 3273,
    "electronegativity": 1.13,
    "electronAffinity": "-",
    "ionizationEnergy": "-",
    "atomicRadius": 236,
    "configuration": "[Xe] 4f⁵ 6s²",
    "magnetic": "paramagnetic",
    "discoverer": "Jacob A. Marinsky, Lawrence E. Glendenin & Charles D. Coryell",
    "discoveryYear": 1945
  },
  {
    "id": "Sm",
    "symbol": "Sm",
    "name": "Samarium",
    "atomicNumber": 62,
    "mass": 150.4,
    "group": "Lanthanoids",
    "period": 6,
    "block": "f",
    "category": "lanthanide",
    "state": "Solid",
    "appearance": "silvery white",
    "density": 7.52,
    "meltingPoint": 1347,
    "boilingPoint": 2067,
    "electronegativity": 1.17,
    "electronAffinity": "-",
    "ionizationEnergy": 5.644,
    "atomicRadius": 229,
    "configuration": "[Xe] 4f⁶ 6s²",
    "magnetic": "paramagnetic",
    "discoverer": "Lecoq de Boisbaudran",
    "discoveryYear": 1879
  },
  {
    "id": "Eu",
    "symbol": "Eu",
    "name": "Europium",
    "atomicNumber": 63,
    "mass": 151.964,
    "group": "Lanthanoids",
    "period": 6,
    "block": "f",
    "category": "lanthanide",
    "state": "Solid",
    "appearance": "silvery white with a pale yellow tint",
    "density": 5.24,
    "meltingPoint": 1095,
    "boilingPoint": 1802,
    "electronegativity": 0.99,
    "electronAffinity": "-",
    "ionizationEnergy": 5.67,
    "atomicRadius": 233,
    "configuration": "[Xe] 4f⁷ 6s²",
    "magnetic": "paramagnetic",
    "discoverer": "Eugène-Anatole Demarçay",
    "discoveryYear": 1896
  },
  {
    "id": "Gd",
    "symbol": "Gd",
    "name": "Gadolinium",
    "atomicNumber": 64,
    "mass": 157.25,
    "group": "Lanthanoids",
    "period": 6,
    "block": "f",
    "category": "lanthanide",
    "state": "Solid",
    "appearance": "silvery white",
    "density": 7.9,
    "meltingPoint": 1586,
    "boilingPoint": 3546,
    "electronegativity": 1.2,
    "electronAffinity": "-",
    "ionizationEnergy": 6.15,
    "atomicRadius": 237,
    "configuration": "[Xe] 4f⁷ 5d¹ 6s²",
    "magnetic": "ferromagnetic / paramagnetic",
    "discoverer": "Jean Charles Galissard de Marignac",
    "discoveryYear": 1880
  },
  {
    "id": "Tb",
    "symbol": "Tb",
    "name": "Terbium",
    "atomicNumber": 65,
    "mass": 158.92535,
    "group": "Lanthanoids",
    "period": 6,
    "block": "f",
    "category": "lanthanide",
    "state": "Solid",
    "appearance": "silvery white",
    "density": 8.23,
    "meltingPoint": 1629,
    "boilingPoint": 3503,
    "electronegativity": 1.1,
    "electronAffinity": "-",
    "ionizationEnergy": 5.863,
    "atomicRadius": 221,
    "configuration": "[Xe] 4f⁹ 6s²",
    "magnetic": "paramagnetic",
    "discoverer": "Carl Gustaf Mosander",
    "discoveryYear": 1843
  },
  {
    "id": "Dy",
    "symbol": "Dy",
    "name": "Dysprosium",
    "atomicNumber": 66,
    "mass": 162.5,
    "group": "Lanthanoids",
    "period": 6,
    "block": "f",
    "category": "lanthanide",
    "state": "Solid",
    "appearance": "silvery white",
    "density": 8.55,
    "meltingPoint": 1685,
    "boilingPoint": 2840,
    "electronegativity": 1.22,
    "electronAffinity": "-",
    "ionizationEnergy": 5.938,
    "atomicRadius": 229,
    "configuration": "[Xe] 4f¹⁰ 6s²",
    "magnetic": "paramagnetic",
    "discoverer": "Lecoq de Boisbaudran",
    "discoveryYear": 1886
  },
  {
    "id": "Ho",
    "symbol": "Ho",
    "name": "Holmium",
    "atomicNumber": 67,
    "mass": 164.93033,
    "group": "Lanthanoids",
    "period": 6,
    "block": "f",
    "category": "lanthanide",
    "state": "Solid",
    "appearance": "silvery white",
    "density": 8.8,
    "meltingPoint": 1747,
    "boilingPoint": 2973,
    "electronegativity": 1.23,
    "electronAffinity": "-",
    "ionizationEnergy": 6.021,
    "atomicRadius": 216,
    "configuration": "[Xe] 4f¹¹ 6s²",
    "magnetic": "paramagnetic",
    "discoverer": "Per Theodor Cleve, Jacques-Louis Soret & Marc Delafontaine",
    "discoveryYear": 1878
  },
  {
    "id": "Er",
    "symbol": "Er",
    "name": "Erbium",
    "atomicNumber": 68,
    "mass": 167.26,
    "group": "Lanthanoids",
    "period": 6,
    "block": "f",
    "category": "lanthanide",
    "state": "Solid",
    "appearance": "silvery white",
    "density": 9.07,
    "meltingPoint": 1802,
    "boilingPoint": 3141,
    "electronegativity": 1.24,
    "electronAffinity": "-",
    "ionizationEnergy": 6.108,
    "atomicRadius": 235,
    "configuration": "[Xe] 4f¹² 6s²",
    "magnetic": "paramagnetic",
    "discoverer": "Carl Gustaf Mosander",
    "discoveryYear": 1843
  },
  {
    "id": "Tm",
    "symbol": "Tm",
    "name": "Thulium",
    "atomicNumber": 69,
    "mass": 168.93422,
    "group": "Lanthanoids",
    "period": 6,
    "block": "f",
    "category": "lanthanide",
    "state": "Solid",
    "appearance": "silvery gray",
    "density": 9.32,
    "meltingPoint": 1818,
    "boilingPoint": 2223,
    "electronegativity": 1.25,
    "electronAffinity": "-",
    "ionizationEnergy": 6.184,
    "atomicRadius": 227,
    "configuration": "[Xe] 4f¹³ 6s²",
    "magnetic": "paramagnetic",
    "discoverer": "Per Theodor Cleve",
    "discoveryYear": 1879
  },
  {
    "id": "Yb",
    "symbol": "Yb",
    "name": "Ytterbium",
    "atomicNumber": 70,
    "mass": 173.05,
    "group": "Lanthanoids",
    "period": 6,
    "block": "f",
    "category": "lanthanide",
    "state": "Solid",
    "appearance": "silvery white with a pale yellow tint",
    "density": 6.9,
    "meltingPoint": 1092,
    "boilingPoint": 1469,
    "electronegativity": 1.1,
    "electronAffinity": "-",
    "ionizationEnergy": 6.254,
    "atomicRadius": 242,
    "configuration": "[Xe] 4f¹⁴ 6s²",
    "magnetic": "paramagnetic",
    "discoverer": "Jean Charles Galissard de Marignac",
    "discoveryYear": 1878
  },
  {
    "id": "Lu",
    "symbol": "Lu",
    "name": "Lutetium",
    "atomicNumber": 71,
    "mass": 174.9667,
    "group": "Lanthanoids",
    "period": 6,
    "block": "d",
    "category": "lanthanide",
    "state": "Solid",
    "appearance": "silvery white",
    "density": 9.84,
    "meltingPoint": 1936,
    "boilingPoint": 3675,
    "electronegativity": 1.27,
    "electronAffinity": "-",
    "ionizationEnergy": 5.426,
    "atomicRadius": 221,
    "configuration": "[Xe] 4f¹⁴ 5d¹ 6s²",
    "magnetic": "paramagnetic",
    "discoverer": "Carl Auer von Weisbach & Georges Urbain",
    "discoveryYear": 1906
  },
  {
    "id": "Hf",
    "symbol": "Hf",
    "name": "Hafnium",
    "atomicNumber": 72,
    "mass": 178.49,
    "group": "4B",
    "period": 6,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "steel gray",
    "density": 13.3,
    "meltingPoint": 2506,
    "boilingPoint": 4876,
    "electronegativity": 1.3,
    "electronAffinity": "-",
    "ionizationEnergy": 6.825,
    "atomicRadius": 208,
    "configuration": "[Xe] 4f¹⁴ 5d² 6s²",
    "magnetic": "paramagnetic",
    "discoverer": "Dirk Coaster & George de Hevesy",
    "discoveryYear": 1922
  },
  {
    "id": "Ta",
    "symbol": "Ta",
    "name": "Tantalum",
    "atomicNumber": 73,
    "mass": 180.9479,
    "group": "5B",
    "period": 6,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "gray blue",
    "density": 16.4,
    "meltingPoint": 3290,
    "boilingPoint": 5731,
    "electronegativity": 1.5,
    "electronAffinity": 0.322,
    "ionizationEnergy": 7.549,
    "atomicRadius": 200,
    "configuration": "[Xe] 4f¹⁴ 5d³ 6s²",
    "magnetic": "paramagnetic",
    "discoverer": "Anders Gustaf Ekeberg",
    "discoveryYear": 1802
  },
  {
    "id": "W",
    "symbol": "W",
    "name": "Tungsten",
    "atomicNumber": 74,
    "mass": 183.84,
    "group": "6B",
    "period": 6,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "grayish white, lustrous",
    "density": 19.3,
    "meltingPoint": 3695,
    "boilingPoint": 5828,
    "electronegativity": 2.36,
    "electronAffinity": 0.815,
    "ionizationEnergy": 7.864,
    "atomicRadius": 193,
    "configuration": "[Xe] 4f¹⁴ 5d⁴ 6s²",
    "magnetic": "paramagnetic",
    "discoverer": "Juan José Elhuyar & Fausto Elhuyar",
    "discoveryYear": 1783
  },
  {
    "id": "Re",
    "symbol": "Re",
    "name": "Rhenium",
    "atomicNumber": 75,
    "mass": 186.207,
    "group": "7B",
    "period": 6,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "silvery-grayish",
    "density": 20.8,
    "meltingPoint": 3459,
    "boilingPoint": 5869,
    "electronegativity": 1.9,
    "electronAffinity": 0.15,
    "ionizationEnergy": 7.833,
    "atomicRadius": 188,
    "configuration": "[Xe] 4f¹⁴ 5d⁵ 6s²",
    "magnetic": "paramagnetic",
    "discoverer": "Masataka Ogawa",
    "discoveryYear": 1908
  },
  {
    "id": "Os",
    "symbol": "Os",
    "name": "Osmium",
    "atomicNumber": 76,
    "mass": 190.2,
    "group": "8B",
    "period": 6,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "silvery blue cast",
    "density": 22.57,
    "meltingPoint": 3306,
    "boilingPoint": 5285,
    "electronegativity": 2.2,
    "electronAffinity": 1.1,
    "ionizationEnergy": 8.438,
    "atomicRadius": 185,
    "configuration": "[Xe] 4f¹⁴ 5d⁶ 6s²",
    "magnetic": "paramagnetic",
    "discoverer": "Smithson Tennant",
    "discoveryYear": 1803
  },
  {
    "id": "Ir",
    "symbol": "Ir",
    "name": "Iridium",
    "atomicNumber": 77,
    "mass": 192.22,
    "group": "8B",
    "period": 6,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "silvery white",
    "density": 22.42,
    "meltingPoint": 2719,
    "boilingPoint": 4701,
    "electronegativity": 2.2,
    "electronAffinity": 1.565,
    "ionizationEnergy": 8.967,
    "atomicRadius": 180,
    "configuration": "[Xe] 4f¹⁴ 5d⁷ 6s²",
    "magnetic": "paramagnetic",
    "discoverer": "Smithson Tennant",
    "discoveryYear": 1803
  },
  {
    "id": "Pt",
    "symbol": "Pt",
    "name": "Platinum",
    "atomicNumber": 78,
    "mass": 195.08,
    "group": "8B",
    "period": 6,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "silvery white",
    "density": 21.46,
    "meltingPoint": 2041.55,
    "boilingPoint": 4098,
    "electronegativity": 2.28,
    "electronAffinity": 2.128,
    "ionizationEnergy": 8.958,
    "atomicRadius": 177,
    "configuration": "[Xe] 4f¹⁴ 5d⁹ 6s¹",
    "magnetic": "paramagnetic",
    "discoverer": "Antonio de Ulloa",
    "discoveryYear": 1735
  },
  {
    "id": "Au",
    "symbol": "Au",
    "name": "Gold",
    "atomicNumber": 79,
    "mass": 196.96657,
    "group": "1B",
    "period": 6,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "metallic yellow",
    "density": 19.282,
    "meltingPoint": 1337.33,
    "boilingPoint": 3129,
    "electronegativity": 2.54,
    "electronAffinity": 2.309,
    "ionizationEnergy": 9.225,
    "atomicRadius": 174,
    "configuration": "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",
    "magnetic": "diamagnetic",
    "discoverer": "Middle East",
    "discoveryYear": "before 6000 BC"
  },
  {
    "id": "Hg",
    "symbol": "Hg",
    "name": "Mercury",
    "atomicNumber": 80,
    "mass": 200.59,
    "group": "2B",
    "period": 6,
    "block": "d",
    "category": "transition metal",
    "state": "Liquid",
    "appearance": "shiny, silvery liquid",
    "density": 13.5336,
    "meltingPoint": 234.32,
    "boilingPoint": 629.88,
    "electronegativity": 2.0,
    "electronAffinity": "-",
    "ionizationEnergy": 10.437,
    "atomicRadius": 151,
    "configuration": "[Xe] 4f¹⁴ 5d¹⁰ 6s²",
    "magnetic": "diamagnetic",
    "discoverer": "Ancient Egyptians",
    "discoveryYear": "before 1500 BC"
  },
  {
    "id": "Tl",
    "symbol": "Tl",
    "name": "Thallium",
    "atomicNumber": 81,
    "mass": 204.383,
    "group": "3A",
    "period": 6,
    "block": "p",
    "category": "metal",
    "state": "Solid",
    "appearance": "silvery white",
    "density": 11.8,
    "meltingPoint": 577,
    "boilingPoint": 1746,
    "electronegativity": 1.62,
    "electronAffinity": 0.2,
    "ionizationEnergy": 6.108,
    "atomicRadius": 170,
    "configuration": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",
    "magnetic": "diamagnetic",
    "discoverer": "William Crookes",
    "discoveryYear": 1861
  },
  {
    "id": "Pb",
    "symbol": "Pb",
    "name": "Lead",
    "atomicNumber": 82,
    "mass": 207,
    "group": "4A",
    "period": 6,
    "block": "p",
    "category": "metal",
    "state": "Solid",
    "appearance": "metallic gray",
    "density": 11.342,
    "meltingPoint": 600.61,
    "boilingPoint": 2022,
    "electronegativity": 2.33,
    "electronAffinity": 0.36,
    "ionizationEnergy": 7.417,
    "atomicRadius": 175,
    "configuration": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
    "magnetic": "diamagnetic",
    "discoverer": "Middle East",
    "discoveryYear": "7000 BC"
  },
  {
    "id": "Bi",
    "symbol": "Bi",
    "name": "Bismuth",
    "atomicNumber": 83,
    "mass": 208.9804,
    "group": "5A",
    "period": 6,
    "block": "p",
    "category": "metal",
    "state": "Solid",
    "appearance": "lustrous brownish silver",
    "density": 9.807,
    "meltingPoint": 544.55,
    "boilingPoint": 1837,
    "electronegativity": 2.02,
    "electronAffinity": 0.946,
    "ionizationEnergy": 7.285,
    "atomicRadius": 160,
    "configuration": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",
    "magnetic": "diamagnetic",
    "discoverer": "Arabic Alchemists",
    "discoveryYear": "before AD 1000"
  },
  {
    "id": "Po",
    "symbol": "Po",
    "name": "Polonium",
    "atomicNumber": 84,
    "mass": 208.98243,
    "group": "6A",
    "period": 6,
    "block": "p",
    "category": "metalloid",
    "state": "Solid",
    "appearance": "silvery",
    "density": 9.32,
    "meltingPoint": 527,
    "boilingPoint": 1235,
    "electronegativity": 2.0,
    "electronAffinity": 1.9,
    "ionizationEnergy": 8.417,
    "atomicRadius": 190,
    "configuration": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",
    "magnetic": "nonmagnetic",
    "discoverer": "Pierre & Marrie Curie",
    "discoveryYear": 1898
  },
  {
    "id": "At",
    "symbol": "At",
    "name": "Astatine",
    "atomicNumber": 85,
    "mass": 209.98715,
    "group": "7A",
    "period": 6,
    "block": "p",
    "category": "halogen",
    "state": "Solid",
    "appearance": "unknown, probably metallic",
    "density": 7,
    "meltingPoint": 575,
    "boilingPoint": "-",
    "electronegativity": 2.2,
    "electronAffinity": 2.8,
    "ionizationEnergy": "-",
    "atomicRadius": "-",
    "configuration": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",
    "magnetic": "-",
    "discoverer": "Dale R. Corson, Kenneth Ross Mackenzie & Emilio Segrè",
    "discoveryYear": 1940
  },
  {
    "id": "Rn",
    "symbol": "Rn",
    "name": "Radon",
    "atomicNumber": 86,
    "mass": 222.01758,
    "group": "8A",
    "period": 6,
    "block": "p",
    "category": "noble gas",
    "state": "Gas",
    "appearance": "colorless gas",
    "density": 0.00973,
    "meltingPoint": 202,
    "boilingPoint": 211.45,
    "electronegativity": "-",
    "electronAffinity": "-",
    "ionizationEnergy": "-",
    "atomicRadius": "-",
    "configuration": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",
    "magnetic": "nonmagnetic",
    "discoverer": "Ernest Rutherford & Robert B. Owens",
    "discoveryYear": 1899
  },
  {
    "id": "Fr",
    "symbol": "Fr",
    "name": "Francium",
    "atomicNumber": 87,
    "mass": 223.01973,
    "group": "1A",
    "period": 7,
    "block": "s",
    "category": "alkali metal",
    "state": "Solid",
    "appearance": "-",
    "density": 5,
    "meltingPoint": 300,
    "boilingPoint": "-",
    "electronegativity": 0.7,
    "electronAffinity": 0.47,
    "ionizationEnergy": 4.072,
    "atomicRadius": "-",
    "configuration": "[Rn] 7s¹",
    "magnetic": "paramagnetic",
    "discoverer": "Marguerite Perey",
    "discoveryYear": 1939
  },
  {
    "id": "Ra",
    "symbol": "Ra",
    "name": "Radium",
    "atomicNumber": 88,
    "mass": 226.02541,
    "group": "2A",
    "period": 7,
    "block": "s",
    "category": "alkaline earth metal",
    "state": "Solid",
    "appearance": "silvery white metallic",
    "density": 5,
    "meltingPoint": 973,
    "boilingPoint": 1413,
    "electronegativity": 0.9,
    "electronAffinity": "-",
    "ionizationEnergy": 5.278,
    "atomicRadius": "-",
    "configuration": "[Rn] 7s²",
    "magnetic": "nonmagnetic",
    "discoverer": "Pierre & Marie Curie",
    "discoveryYear": 1898
  },
  {
    "id": "Ac",
    "symbol": "Ac",
    "name": "Actinium",
    "atomicNumber": 89,
    "mass": 227.02775,
    "group": "Actinoids",
    "period": 7,
    "block": "f",
    "category": "actinide",
    "state": "Solid",
    "appearance": "silvery-white, glowing with an eerie blue light, sometimes with a golden cast",
    "density": 10.07,
    "meltingPoint": 1324,
    "boilingPoint": 3471,
    "electronegativity": 1.1,
    "electronAffinity": "-",
    "ionizationEnergy": 5.17,
    "atomicRadius": "-",
    "configuration": "[Rn] 6d¹ 7s²",
    "magnetic": "-",
    "discoverer": "Friedrich Oskar Giesel",
    "discoveryYear": 1902
  },
  {
    "id": "Th",
    "symbol": "Th",
    "name": "Thorium",
    "atomicNumber": 90,
    "mass": 232.038,
    "group": "Actinoids",
    "period": 7,
    "block": "f",
    "category": "actinide",
    "state": "Solid",
    "appearance": "silvery",
    "density": 11.72,
    "meltingPoint": 2023,
    "boilingPoint": 5061,
    "electronegativity": 1.3,
    "electronAffinity": "-",
    "ionizationEnergy": 6.08,
    "atomicRadius": "-",
    "configuration": "[Rn] 6d² 7s²",
    "magnetic": "paramagnetic",
    "discoverer": "Jöns Jakob Berzelius",
    "discoveryYear": 1829
  },
  {
    "id": "Pa",
    "symbol": "Pa",
    "name": "Protactinium",
    "atomicNumber": 91,
    "mass": 231.03588,
    "group": "Actinoids",
    "period": 7,
    "block": "f",
    "category": "actinide",
    "state": "Solid",
    "appearance": "bright, silvery metallic luster",
    "density": 15.37,
    "meltingPoint": 1845,
    "boilingPoint": "-",
    "electronegativity": 1.5,
    "electronAffinity": "-",
    "ionizationEnergy": 5.89,
    "atomicRadius": "-",
    "configuration": "[Rn] 5f² 6d¹ 7s²",
    "magnetic": "paramagnetic",
    "discoverer": "Kasimir Fajans & Oswald Hemluth Göhring",
    "discoveryYear": 1913
  },
  {
    "id": "U",
    "symbol": "U",
    "name": "Uranium",
    "atomicNumber": 92,
    "mass": 238.0289,
    "group": "Actinoids",
    "period": 7,
    "block": "f",
    "category": "actinide",
    "state": "Solid",
    "appearance": "silvery gray metallic, corrodes to a spalling black oxide coat in air",
    "density": 18.95,
    "meltingPoint": 1408,
    "boilingPoint": 4404,
    "electronegativity": 1.38,
    "electronAffinity": "-",
    "ionizationEnergy": 6.194,
    "atomicRadius": "-",
    "configuration": "[Rn] 5f³ 6d¹ 7s²",
    "magnetic": "paramagnetic",
    "discoverer": "Martin Heinrich Klaproth",
    "discoveryYear": 1789
  },
  {
    "id": "Np",
    "symbol": "Np",
    "name": "Neptunium",
    "atomicNumber": 93,
    "mass": 237.048172,
    "group": "Actinoids",
    "period": 7,
    "block": "f",
    "category": "actinide",
    "state": "Solid",
    "appearance": "silvery metallic",
    "density": 20.25,
    "meltingPoint": 917,
    "boilingPoint": 4175,
    "electronegativity": 1.36,
    "electronAffinity": "-",
    "ionizationEnergy": 6.265,
    "atomicRadius": "-",
    "configuration": "[Rn] 5f⁴ 6d¹ 7s²",
    "magnetic": "paramagnetic",
    "discoverer": "Edwin McMillan & Philip H. Abelson",
    "discoveryYear": 1940
  },
  {
    "id": "Pu",
    "symbol": "Pu",
    "name": "Plutonium",
    "atomicNumber": 94,
    "mass": 244.0642,
    "group": "Actinoids",
    "period": 7,
    "block": "f",
    "category": "actinide",
    "state": "Solid",
    "appearance": "silvery white, tarnishing to dark gray in air",
    "density": 19.84,
    "meltingPoint": 913,
    "boilingPoint": 3501,
    "electronegativity": 1.28,
    "electronAffinity": "-",
    "ionizationEnergy": 6.026,
    "atomicRadius": "-",
    "configuration": "[Rn] 5f⁶ 7s²",
    "magnetic": "paramagnetic",
    "discoverer": "Glenn T. Seaborg, Arthur Wahl, Joseph W. Kennedy & Edwin McMillan",
    "discoveryYear": "1940-1941"
  },
  {
    "id": "Am",
    "symbol": "Am",
    "name": "Americium",
    "atomicNumber": 95,
    "mass": 243.06138,
    "group": "Actinoids",
    "period": 7,
    "block": "f",
    "category": "actinide",
    "state": "Solid",
    "appearance": "silvery white",
    "density": 13.69,
    "meltingPoint": 1449,
    "boilingPoint": 2284,
    "electronegativity": 1.13,
    "electronAffinity": "-",
    "ionizationEnergy": 5.97,
    "atomicRadius": "-",
    "configuration": "[Rn] 5f⁷ 7s²",
    "magnetic": "paramagnetic",
    "discoverer": "Glenn T. Seaborg, Ralph A. James, Leon O. Morgan & Albert Ghiorso",
    "discoveryYear": 1944
  },
  {
    "id": "Cm",
    "symbol": "Cm",
    "name": "Curium",
    "atomicNumber": 96,
    "mass": 247.07035,
    "group": "Actinoids",
    "period": 7,
    "block": "f",
    "category": "actinide",
    "state": "Solid",
    "appearance": "silvery metallic, glows purple in the dark",
    "density": 13.51,
    "meltingPoint": 1618,
    "boilingPoint": 3400,
    "electronegativity": 1.28,
    "electronAffinity": "-",
    "ionizationEnergy": 5.991,
    "atomicRadius": "-",
    "configuration": "[Rn] 5f⁷ 6d¹ 7s²",
    "magnetic": "antiferromagnetic / paramagnetic",
    "discoverer": "Glenn T. Seaborg, Ralph A. James & Albert Ghiorso",
    "discoveryYear": 1944
  },
  {
    "id": "Bk",
    "symbol": "Bk",
    "name": "Berkelium",
    "atomicNumber": 97,
    "mass": 247.07031,
    "group": "Actinoids",
    "period": 7,
    "block": "f",
    "category": "actinide",
    "state": "Solid",
    "appearance": "silvery",
    "density": 14,
    "meltingPoint": 1323,
    "boilingPoint": "-",
    "electronegativity": 1.3,
    "electronAffinity": "-",
    "ionizationEnergy": 6.197,
    "atomicRadius": "-",
    "configuration": "[Rn] 5f⁹ 7s²",
    "magnetic": "paramagnetic",
    "discoverer": "Lawrence Berkeley National Laboratory",
    "discoveryYear": 1949
  },
  {
    "id": "Cf",
    "symbol": "Cf",
    "name": "Californium",
    "atomicNumber": 98,
    "mass": 251.07959,
    "group": "Actinoids",
    "period": 7,
    "block": "f",
    "category": "actinide",
    "state": "Solid",
    "appearance": "silvery",
    "density": "-",
    "meltingPoint": 1173,
    "boilingPoint": "-",
    "electronegativity": 1.3,
    "electronAffinity": "-",
    "ionizationEnergy": 6.281,
    "atomicRadius": "-",
    "configuration": "[Rn] 5f¹⁰ 7s²",
    "magnetic": "-",
    "discoverer": "S. G. Thompson, K. Street, Jr., A. Ghiorso & Glenn T. Seaborg",
    "discoveryYear": 1950
  },
  {
    "id": "Es",
    "symbol": "Es",
    "name": "Einsteinium",
    "atomicNumber": 99,
    "mass": 252.083,
    "group": "Actinoids",
    "period": 7,
    "block": "f",
    "category": "actinide",
    "state": "Solid",
    "appearance": "silvery, glows blue in the dark",
    "density": "-",
    "meltingPoint": "-",
    "boilingPoint": "-",
    "electronegativity": 1.3,
    "electronAffinity": "-",
    "ionizationEnergy": 6.42,
    "atomicRadius": "-",
    "configuration": "[Rn] 5f¹¹ 7s²",
    "magnetic": "paramagnetic",
    "discoverer": "Lawrence Berkeley National Laboratory",
    "discoveryYear": 1952
  },
  {
    "id": "Fm",
    "symbol": "Fm",
    "name": "Fermium",
    "atomicNumber": 100,
    "mass": 257.09511,
    "group": "Actinoids",
    "period": 7,
    "block": "f",
    "category": "actinide",
    "state": "Solid",
    "appearance": "-",
    "density": "-",
    "meltingPoint": "-",
    "boilingPoint": "-",
    "electronegativity": 1.3,
    "electronAffinity": "-",
    "ionizationEnergy": 6.5,
    "atomicRadius": "-",
    "configuration": "[Rn] 5f¹² 7s²",
    "magnetic": "-",
    "discoverer": "Lawrence Berkeley National Laboratory",
    "discoveryYear": 1953
  },
  {
    "id": "Md",
    "symbol": "Md",
    "name": "Mendelevium",
    "atomicNumber": 101,
    "mass": 258.09843,
    "group": "Actinoids",
    "period": 7,
    "block": "f",
    "category": "actinide",
    "state": "Solid",
    "appearance": "-",
    "density": "-",
    "meltingPoint": 1100,
    "boilingPoint": "-",
    "electronegativity": 1.3,
    "electronAffinity": "-",
    "ionizationEnergy": 6.58,
    "atomicRadius": "-",
    "configuration": "[Rn] 5f¹³ 7s²",
    "magnetic": "-",
    "discoverer": "Lawrence Berkeley National Laboratory",
    "discoveryYear": 1955
  },
  {
    "id": "No",
    "symbol": "No",
    "name": "Nobelium",
    "atomicNumber": 102,
    "mass": 259.101,
    "group": "Actinoids",
    "period": 7,
    "block": "f",
    "category": "actinide",
    "state": "Solid",
    "appearance": "-",
    "density": "-",
    "meltingPoint": 1100,
    "boilingPoint": "-",
    "electronegativity": 1.3,
    "electronAffinity": "-",
    "ionizationEnergy": 6.65,
    "atomicRadius": "-",
    "configuration": "[Rn] 5f¹⁴ 7s²",
    "magnetic": "-",
    "discoverer": "Joint Institute for Nuclear Research",
    "discoveryYear": 1965
  },
  {
    "id": "Lr",
    "symbol": "Lr",
    "name": "Lawrencium",
    "atomicNumber": 103,
    "mass": 266.12,
    "group": "Actinoids",
    "period": 7,
    "block": "d",
    "category": "actinide",
    "state": "Solid",
    "appearance": "silvery (prediction)",
    "density": "-",
    "meltingPoint": 1900,
    "boilingPoint": "-",
    "electronegativity": 1.3,
    "electronAffinity": "-",
    "ionizationEnergy": "-",
    "atomicRadius": "-",
    "configuration": "[Rn] 5f¹⁴ 6d¹ 7s²",
    "magnetic": "-",
    "discoverer": "Lawrence Berkeley National Laboratory & Joint Institute for Nuclear Research",
    "discoveryYear": "1961-1971"
  },
  {
    "id": "Rf",
    "symbol": "Rf",
    "name": "Rutherfordium",
    "atomicNumber": 104,
    "mass": 267.122,
    "group": "4B",
    "period": 7,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "-",
    "density": "-",
    "meltingPoint": 105,
    "boilingPoint": "-",
    "electronegativity": 1.3,
    "electronAffinity": "-",
    "ionizationEnergy": "-",
    "atomicRadius": "-",
    "configuration": "[Rn] 5f¹⁴ 6d² 7s²",
    "magnetic": "-",
    "discoverer": "Joint Institute for Nuclear Research & Lawrence Berkeley National Laboratory",
    "discoveryYear": 1969
  },
  {
    "id": "Db",
    "symbol": "Db",
    "name": "Dubnium",
    "atomicNumber": 105,
    "mass": 268.126,
    "group": "5B",
    "period": 7,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "-",
    "density": "-",
    "meltingPoint": "-",
    "boilingPoint": "-",
    "electronegativity": 1.3,
    "electronAffinity": "-",
    "ionizationEnergy": "-",
    "atomicRadius": "-",
    "configuration": "[Rn] 5f¹⁴ 6d³ 7s²",
    "magnetic": "-",
    "discoverer": "Lawrence Berkeley National Laboratory & Joint Institute for Nuclear Research",
    "discoveryYear": 1970
  },
  {
    "id": "Sg",
    "symbol": "Sg",
    "name": "Seaborgium",
    "atomicNumber": 106,
    "mass": 269.128,
    "group": "6B",
    "period": 7,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "-",
    "density": "-",
    "meltingPoint": "-",
    "boilingPoint": "-",
    "electronegativity": 1.3,
    "electronAffinity": "-",
    "ionizationEnergy": "-",
    "atomicRadius": "-",
    "configuration": "[Rn] 5f¹⁴ 6d⁴ 7s²",
    "magnetic": "-",
    "discoverer": "Lawrence Berkeley National Laboratory",
    "discoveryYear": 1974
  },
  {
    "id": "Bh",
    "symbol": "Bh",
    "name": "Bohrium",
    "atomicNumber": 107,
    "mass": 270.133,
    "group": "7B",
    "period": 7,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "-",
    "density": "-",
    "meltingPoint": "-",
    "boilingPoint": "-",
    "electronegativity": 1.3,
    "electronAffinity": "-",
    "ionizationEnergy": "-",
    "atomicRadius": "-",
    "configuration": "[Rn] 5f¹⁴ 6d⁵ 7s²",
    "magnetic": "-",
    "discoverer": "Gesellschaft für Schwerionenforschung",
    "discoveryYear": 1981
  },
  {
    "id": "Hs",
    "symbol": "Hs",
    "name": "Hassium",
    "atomicNumber": 108,
    "mass": 269.1336,
    "group": "8B",
    "period": 7,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "-",
    "density": "-",
    "meltingPoint": "-",
    "boilingPoint": "-",
    "electronegativity": 1.3,
    "electronAffinity": "-",
    "ionizationEnergy": "-",
    "atomicRadius": "-",
    "configuration": "[Rn] 5f¹⁴ 6d⁶ 7s²",
    "magnetic": "-",
    "discoverer": "Gesellschaft für Schwerionenforschung",
    "discoveryYear": 1984
  },
  {
    "id": "Mt",
    "symbol": "Mt",
    "name": "Meitnerium",
    "atomicNumber": 109,
    "mass": 277.154,
    "group": "8B",
    "period": 7,
    "block": "d",
    "category": "unknown",
    "state": "Solid",
    "appearance": "-",
    "density": "-",
    "meltingPoint": "-",
    "boilingPoint": "-",
    "electronegativity": 1.3,
    "electronAffinity": "-",
    "ionizationEnergy": "-",
    "atomicRadius": "-",
    "configuration": "[Rn] 5f¹⁴ 6d⁷ 7s²",
    "magnetic": "-",
    "discoverer": "Gesellschaft für Schwerionenforschung",
    "discoveryYear": 1982
  },
  {
    "id": "Ds",
    "symbol": "Ds",
    "name": "Darmstadtium",
    "atomicNumber": 110,
    "mass": 282.166,
    "group": "8B",
    "period": 7,
    "block": "d",
    "category": "unknown",
    "state": "Solid",
    "appearance": "-",
    "density": "-",
    "meltingPoint": "-",
    "boilingPoint": "-",
    "electronegativity": 1.3,
    "electronAffinity": "-",
    "ionizationEnergy": "-",
    "atomicRadius": "-",
    "configuration": "[Rn] 5f¹⁴ 6d⁹ 7s¹",
    "magnetic": "-",
    "discoverer": "Gesellschaft für Schwerionenforschung",
    "discoveryYear": 1994
  },
  {
    "id": "Rg",
    "symbol": "Rg",
    "name": "Roentgenium",
    "atomicNumber": 111,
    "mass": 282.169,
    "group": "1B",
    "period": 7,
    "block": "d",
    "category": "unknown",
    "state": "Solid",
    "appearance": "-",
    "density": "-",
    "meltingPoint": "-",
    "boilingPoint": "-",
    "electronegativity": 1.3,
    "electronAffinity": "-",
    "ionizationEnergy": "-",
    "atomicRadius": "-",
    "configuration": "[Rn] 5f¹⁴ 6d¹⁰ 7s¹",
    "magnetic": "-",
    "discoverer": "Gesellschaft für Schwerionenforschung",
    "discoveryYear": 1994
  },
  {
    "id": "Cn",
    "symbol": "Cn",
    "name": "Copernicium",
    "atomicNumber": 112,
    "mass": 286.179,
    "group": "2B",
    "period": 7,
    "block": "d",
    "category": "transition metal",
    "state": "Solid",
    "appearance": "-",
    "density": "-",
    "meltingPoint": "-",
    "boilingPoint": "-",
    "electronegativity": 1.3,
    "electronAffinity": "-",
    "ionizationEnergy": "-",
    "atomicRadius": "-",
    "configuration": "[Rn] 5f¹⁴ 6d¹⁰ 7s²",
    "magnetic": "-",
    "discoverer": "Gesellschaft für Schwerionenforschung",
    "discoveryYear": 1996
  },
  {
    "id": "Nh",
    "symbol": "Nh",
    "name": "Nihonium",
    "atomicNumber": 113,
    "mass": 286.182,
    "group": "3A",
    "period": 7,
    "block": "p",
    "category": "metal",
    "state": "Solid",
    "appearance": "-",
    "density": "-",
    "meltingPoint": "-",
    "boilingPoint": "-",
    "electronegativity": 1.3,
    "electronAffinity": "-",
    "ionizationEnergy": "-",
    "atomicRadius": "-",
    "configuration": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",
    "magnetic": "-",
    "discoverer": "Riken (Japan, first undisputed claim); JINR (Russia) & Livermore (US, first announcement)",
    "discoveryYear": "2004 / 2003"
  },
  {
    "id": "Fl",
    "symbol": "Fl",
    "name": "Flerovium",
    "atomicNumber": 114,
    "mass": 290.192,
    "group": "4A",
    "period": 7,
    "block": "p",
    "category": "metal",
    "state": "Solid",
    "appearance": "-",
    "density": "-",
    "meltingPoint": "-",
    "boilingPoint": "-",
    "electronegativity": 1.3,
    "electronAffinity": "-",
    "ionizationEnergy": "-",
    "atomicRadius": "-",
    "configuration": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",
    "magnetic": "-",
    "discoverer": "Joint Institute for Nuclear Research (JINR) & Lawrence Livermore National Laboratory (LLNL)",
    "discoveryYear": 1999
  },
  {
    "id": "Mc",
    "symbol": "Mc",
    "name": "Moscovium",
    "atomicNumber": 115,
    "mass": 290.196,
    "group": "5A",
    "period": 7,
    "block": "p",
    "category": "metal",
    "state": "Solid",
    "appearance": "-",
    "density": "-",
    "meltingPoint": "-",
    "boilingPoint": "-",
    "electronegativity": 1.3,
    "electronAffinity": "-",
    "ionizationEnergy": "-",
    "atomicRadius": "-",
    "configuration": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",
    "magnetic": "-",
    "discoverer": "Joint Institute for Nuclear Research & Lawrence Livermore National Laboratory",
    "discoveryYear": 2003
  },
  {
    "id": "Lv",
    "symbol": "Lv",
    "name": "Livermorium",
    "atomicNumber": 116,
    "mass": 293.205,
    "group": "6A",
    "period": 7,
    "block": "p",
    "category": "metal",
    "state": "Solid",
    "appearance": "-",
    "density": "-",
    "meltingPoint": "-",
    "boilingPoint": "-",
    "electronegativity": 1.3,
    "electronAffinity": "-",
    "ionizationEnergy": "-",
    "atomicRadius": "-",
    "configuration": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",
    "magnetic": "-",
    "discoverer": "Joint Institute for Nuclear Research & Lawrence Livermore National Laboratory",
    "discoveryYear": 2000
  },
  {
    "id": "Ts",
    "symbol": "Ts",
    "name": "Tennessine",
    "atomicNumber": 117,
    "mass": 294.211,
    "group": "7A",
    "period": 7,
    "block": "p",
    "category": "halogen",
    "state": "Solid",
    "appearance": "",
    "density": "-",
    "meltingPoint": "-",
    "boilingPoint": "-",
    "electronegativity": 2.0,
    "electronAffinity": "-",
    "ionizationEnergy": "-",
    "atomicRadius": "-",
    "configuration": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",
    "magnetic": "-",
    "discoverer": "Joint Institute for Nuclear Research, Lawrence Livermore National Laboratory, Vanderbilt University & Oak Ridge National Laboratory",
    "discoveryYear": 2010
  },
  {
    "id": "Og",
    "symbol": "Og",
    "name": "Oganesson",
    "atomicNumber": 118,
    "mass": 295.216,
    "group": "8A",
    "period": 7,
    "block": "p",
    "category": "noble gas",
    "state": "Solid",
    "appearance": "",
    "density": "-",
    "meltingPoint": "-",
    "boilingPoint": "-",
    "electronegativity": "-",
    "electronAffinity": "-",
    "ionizationEnergy": "-",
    "atomicRadius": "-",
    "configuration": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",
    "magnetic": "-",
    "discoverer": "Joint Institute for Nuclear Research & Lawrence Livermore National Laboratory",
    "discoveryYear": 2002
  }
];
